# Generated by Django 3.2.7 on 2022-02-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(default='default', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.CharField(blank=True, default='Blank', max_length=70)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/users/images')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('session_expire', models.DateTimeField(default=users.models.get_deadline)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('app_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('app_secret', models.CharField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='UsedID',
            fields=[
                ('id', models.CharField(default='default', max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('os', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
